### ISSUE TITLE
Jens Jensen name

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#1]
## Points_of_interest
Update to:
**Name** = Jens Jensen Grasslands & Woods Land & Water Reserve

![image](https://cloud.githubusercontent.com/assets/7032169/25011073/b88ccede-2031-11e7-995b-136439f787cd.png)

And need to move it somewhere within the preserve: 42.145174, -88.048758

![image](https://cloud.githubusercontent.com/assets/7032169/25010994/720740ca-2031-11e7-89ac-a765063cb4d9.png)

**Comment by glw** [comment]
same here isnt the old an new update the same?

**Comment by glw** [comment]
Hmm, in GIS the point is showing up in its correct location, I will update the csv's and see if that correct the issue.

**Comment by glw** [comment]
Ive updated the files, the point should show up in the correct location.
