### ISSUE TITLE
Boat rental at Saganashkee Slough Boat Launch

### ISSUE THREAD

**Issue by jim-z** [fpdcc/webmap_data_updates#100]
Boat rentals are now available at Saganashkee slough boat launch.  Update poi boolean.

https://map.fpdcc.com/#/?poi=324-Saganashkee+Slough+Boat+Launch

**Comment by versatilehuman** [comment]
This was marked as updated in issue #93. 

@glw Can you push the latest update so @shua123 can update the live map?

**Comment by shua123** [comment]
Included in c76be98427aef5198aa882d7306fae9bd41846c1

Live map updated.
