### ISSUE TITLE
North Branch Spur at Irene C. Hernandez

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#102]
Unless this is new it the last month, it doesn't exist:

![image](https://user-images.githubusercontent.com/7032169/44414812-5d7aa000-a534-11e8-9414-be1431d09ba6.png)

**Comment by glw** [comment]
Looks like it was recently removed.

**Comment by hallj89** [comment]
Nevermind, I can't edit trails.

**Comment by glw** [comment]
removed
