### ISSUE TITLE
Miami Woods - Cleveland Ave Spur

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#103]
Looks like this hasn't made it on the map yet? We are doing culvert work on it today, but it's not on the web or print maps:

![image](https://user-images.githubusercontent.com/7032169/44732396-ccaf4180-aaaa-11e8-8a4a-46dd9bed87c9.png)

![image](https://user-images.githubusercontent.com/7032169/44732337-abe6ec00-aaaa-11e8-9d82-dbe5d6e707a9.png)

**Comment by glw** [comment]
hmm another new trail, amazing!
