### ISSUE TITLE
Tuma Lake Updates

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#110]
## points_of_interest
**Tuma Lake (poi_info_id=61)**
- no_parking: 1 -> 0
- web_street_addr = S Willow Springs Rd/Flavin Rd, north of 107th St
- parking_info_id = ?
- latitude = 41.706222
- longitude = -87.875417

## poi_desc
**Tuma Lake (poi_info_id=61)**
Remove description:
- description = blank

## parking_entrance
**Tuma Lake (poi_info_id=61)**
- parking_info_id = ?
- name = Tuma Lake
- web_street_addr = S Willow Springs Rd/Flavin Rd, north of 107th St
- web_muni_addr = Cook County, IL 60480
- geom = magic done to 41.706222, -87.875417

**Comment by versatilehuman** [comment]
@glw This opens April 1 if we can do another update by then. It looks like the address didn't get added:

## points_of_interest
Tuma Lake (poi_info_id=61)
- web_street_addr = S Willow Springs Rd/Flavin Rd, north of 107th St

![image](https://user-images.githubusercontent.com/7032169/54220820-3d0a3700-44c0-11e9-8bef-c154282f6edf.png)

**Comment by glw** [comment]
Jim, look for this in acer.pointsofinterest
