### ISSUE TITLE
Assign trail activities at segment level

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#118]
Right now we assign trail activities by trail_type. We would like to move to assigning trail activities by segment.

Thoughts:
1.  Add boolean columns for activities (hiking, cycling, cross_country, equestrian, dogs)
2. Blanket populate data for segments by trail_type:
- paved = hiking, cycling, cross_country, dog_leash
- unpaved = hiking, cycling, cross_country, equestrian, dog_leash
- single track = hiking, cycling, cross_country, equestrian, dog_leash
- primitive = hiking
3. Review each trail system and identify segments that vary from the pattern. 

**Example 1:** Nature Center trails are unpaved, but only allow hiking #119

**Example 2:** Oak Forest Heritage Preserve Trails

No equestrians on these unpaved trails:

![image](https://user-images.githubusercontent.com/7032169/48724080-f3829d00-ebed-11e8-9283-958e38c1013e.png)

**Comment by versatilehuman** [comment]
@glw List of places to manually adjust trail activities:

**Little Red Schoolhouse Trails**
- All segments: hiking

**Sand Ridge Nature Center Trails**
- All segments: hiking

**River Trail Nature Center Trails**
- All segments: hiking

**Trailside Museum Trails**
- All UNPAVED segments: hiking, dog_leash
- Red paved segment (if included): hiking

**Crabtree Nature Center Trails**
- All segments: hiking

**Sagawau Trails**
- All segments: hiking, cross_country

**Oak Forest Heritage Preserve Trails** 
- All segments: hiking, cycling, cross_country, dog_leash

**Salt Creek Trail System**
- All segments: hiking, cycling, cross_country, dog_leash

**Thorn Creek Trail System**
- All segments: hiking, cycling, cross_country, dog_leash

**Tinley Creek Trail System**
- All segments: hiking, cycling, cross_country, dog_leash

**Plum Creek Trail**
- All segments: hiking, cycling, cross_country, dog_leash

**Arie Crown Trails**
- All segments: hiking, cycling, cross_country, dog_leash

**North Branch Trail System**
- Blue Unpaved: hiking, cycling, cross_country, dog_leash

**Comment by glw** [comment]
closed. but this is going to need a closed look into we are representing trails that change their activity depending on location.

**Comment by shua123** [comment]
@glw @versatilehuman  It looks like "hiking", "biking", "cross_country", "equestrian" are the columns that were added to the trails.csv. I do not see anything dog related.

**Comment by versatilehuman** [comment]
@glw will add dogs_leash and no_dogs

@shua123 Now that we are assigning these at segment level, how will that impact the display of icons in the panel for a full segment? 

For example: if there is an error in the data that leaves out or adds an activity on part of a segment, how would that impact the display for the full segment in the panel?

trail_info_id | trail_subsystem | trail_color | hiking | biking | cross_country | equestrian
-- | -- | -- | -- | -- | -- | --
217 | Arie Crown Trail System | black | 1 | 1 | 1 | 0
628 | Arie Crown Trail System | black | 1 | 0 | 1 | 0
785 | Arie Crown Trail System | black | 1 | 1 | 1 | 0
787 | Arie Crown Trail System | black | 1 | **_0_** | 1 | 0
1479 | Arie Crown Trail System | black | 1 | 1 | 1 | 0
220 | Arie Crown Trail System | black | 1 | 1 | 1 | 0
221 | Arie Crown Trail System | black | 1 | 1 | 1 | 0
