### ISSUE TITLE
Add Trail Subsystem IDs

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#121]
To help with individual trail alert embeds:

1. Build table with trail_subsystem column and unique ID column 
2. Join with trails table
3. Hurrah!

**Comment by glw** [comment]
Can we talk about this one again?

**Comment by versatilehuman** [comment]
But we didn't even talk!

**Comment by shua123** [comment]
@glw Historically, trails_desc are joined to trails in the Rails app [using the trails_subsystem field](https://github.com/fpdcc/trailsyserver/blob/development/app/models/trails_info.rb#L4). You have added trail_subsystem_id to the trails.csv export but not to the trails_desc.csv. I think it would make sense to add the trail_subsystem_id to the trails_desc.csv (or add the trail_desc_id to the trails.csv)

Thoughts?

**Comment by versatilehuman** [comment]
@glw I'd say add trail_subsystem_id to trails_desc based on how we do it with pois?

**Comment by glw** [comment]
Sure that would be fine. Am I removing it from the trails table?

**Comment by shua123** [comment]
No the point is to be able to use trail_subsystem_id as the join key between trails and trails_desc unless you think there is a better way to do it.

**Comment by versatilehuman** [comment]
Talked with @glw and in **trails_desc** he'll:
- add **trail_subsystem_id**
- remove **trail_subsystem**
And then upload a new version.

**Comment by glw** [comment]
I see. I can add the id to trails_desc as well. Its actually coming from a look-up table so would be easy to add to the desc table just like we do with the trails table.
