### ISSUE TITLE
Add Fitness stairs and nature play at Dan Ryan

### ISSUE THREAD

**Issue by jim-z** [fpdcc/webmap_data_updates#145]

**Comment by versatilehuman** [comment]
@glw @jim-z Right now fitness stairs, zip line and elk pen are lumped in under "recreation_center" and on the map it displays a "Special Activity" icon. Proposing getting more specific now that we have the new stairs:

- Retiring "recreation_center" column
- Adding "fitness_stairs" column (Swallow Cliff-North & Dan Ryan-West) and displaying Fitness Stairs icon
- Displaying Zip Line icon for Bemis-South
- Not displaying anything on Elk Pen -- it says what it is in the name.

What about Camp Sullivan? Do we want to have a specific climbing wall icon? Or activity barn icon? Or work this into #117?

**Comment by versatilehuman** [comment]
## points_of_interest

- Delete recreation_center column
- Add fitness_stairs column

**Dan Ryan Woods-West** (now Dan Ryan Woods Visitor Center) - poi=313
- fitness_stairs = 1
- natureplay = 1

**Swallow Cliff Woods-North** (poi=123)
- fitness_stairs = 1

## activities
Swallow Cliff Stairs (activities_id=1075)
- atype = fitness stairs

Add:
**Dan Ryan Stairs**
- activities_id = ?
- atype = fitness stairs
- parking_info_id = 
- poi_info_id =
- aname = Dan Ryan Stairs
- geom = 41.736248, -87.679521
