### ISSUE TITLE
Cal-Sag update

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#149]
Looks like there is more built than what we're reflecting on the map, @glw?

**Comment by versatilehuman** [comment]
Found this email from Pam. This would also need to be updated on the PDF version of Major Taylor map.

Ashland to Halsted ( 225 short of 134th St)  is complete.  The bridge over the Little Calumet River is the Forest preserves to maintain. 

The spur from the corner of Halsted and 134th to Whistler Woods should be ready by October 2nd ( trail is complete, just waiting for IDOT to activate ped head signal)

Starting south of the Halsted Ave bridge over the railroad to Indiana Avenue is Riverdale’s section of trail- it is almost complete, they are finishing up pavement striping.

![image](https://user-images.githubusercontent.com/7032169/51269348-e54fc380-1987-11e9-9644-b8494184427c.png)

**Comment by glw** [comment]
@hallj89 this should only require updates of current data. Let me know if you think otherwise after looking at acer.trails.
