### ISSUE TITLE
Thorn Creek vs. Burnham Greenway

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#150]
What's what and why? Is there actual trail or bike lanes or is this just a recommended on-street route from somewhere?

![image](https://user-images.githubusercontent.com/7032169/51201936-069aac00-18c3-11e9-91fc-84cc3e936557.png)

![image](https://user-images.githubusercontent.com/7032169/51201952-11edd780-18c3-11e9-9bff-10b67c2b63ea.png)

![image](https://user-images.githubusercontent.com/7032169/51202487-72c9df80-18c4-11e9-8cb4-634b09218eb3.png)

![image](https://user-images.githubusercontent.com/7032169/51202504-8117fb80-18c4-11e9-8495-6c6435d604f4.png)

**Comment by glw** [comment]
Burnham trail has gaps in it so the Burnham Ave route is/was the temporary on-street connection to the north and south sections. It used to be listed as the Grand Illinois route as well but I think that is changing based on future trail improvements. Also this [website](https://ridewithgps.com/routes/17417147) dedicated to the GIT seems to re-route it along State st. back on to the south section of the actual Burnham trail.

We should probably do the same, itll reduce the amount of off-fpdcc/on-street trails and overall may make more sense when the planned connections are constructed.

**Comment by glw** [comment]
updated connection
