### ISSUE TITLE
No snowmobiles at Miller Meadow-South

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#152]
## points_of_interest
**Miller Meadow-South** (poi_info_id=237)
- snowmobile 1 -> 0

## activities
Delete Miller Meadow Snowmobiling (activities_id=886)

**Comment by glw** [comment]
@hallj89 acer.pointsofinterest change poi_info_id.snowmobile = 0

Ill take care of removing the activity point.
