### ISSUE TITLE
Fix Thatcher area naming issues, add trailhead at Thatcher Woods

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#159]
## points_of_interest
Thatcher Woods Glen (poi=37)
- Delete poi

## activities
Thatcher Pond (activites_id=1043)
- poi_info_id = 233
- parking_info_id = 172

**Comment by glw** [comment]
If we remove this are we making trailside, and thatcher pond (points associated with thatcher glen) a part of the thatcher woods area (ie. pavilion)?

**Comment by versatilehuman** [comment]
Drop by if this doesn't make sense.

The changes in the activities table below would associate the Thatcher Pond waterbody with Trailside. It would be separate from Thatcher. Realizing now though, we need to add fishing at Trailside. And a trailhead at Thatcher.

See updates:

## points_of_interest
Thatcher Woods Glen (poi=37)
- Delete poi

**Trailside Museum of Ntural History** (poi_info_id = 233)
- fishing --> 1

## activities
**Thatcher Pond** (activites_id=1043)
- poi_info_id = 233
- parking_info_id = 172

**Add Thatcher trailhead** (probably around here: 41.897262, -87.828654)

- activities_id = ?
- atype = trailhead
- trail_info_id = ?
- parking_info_id = 27
- poi_info_id = 232
- aname = Thatcher Woods
- geom = ?

**Comment by versatilehuman** [comment]
## activities
@glw Missed this:
**Add Thatcher trailhead** (probably around here: 41.897262, -87.828654)

- activities_id = ?
- atype = trailhead
- trail_info_id = ?
- parking_info_id = 27
- poi_info_id = 232
- aname = Thatcher Woods
- geom = ?
