### ISSUE TITLE
Trail data switcheroos

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#163]
A few issues where it looks like at least names got switched:

## Crabtree

- [ ] Looks like "Black Oak" is actually at Little Red and "Sag Trail" is at Sagawau. Not sure if it's the names or actual segements
- [ ] Segments 2894, 3052, 3053, 3054, 3063, 3013 are paved, but don't have a trail_name or trail_color -- looks like green on the print map?
- [ ] Segement 2895 is paved and named "Link" -- should this just be the same color as all the other paved segments and not have a name?

trail_info_id | trail_subsystem | trail_name | trail_color | trail_type
-- | -- | -- | -- | --
2894 | Crabtree Nature Center Trails |   |   | paved
2895 | Crabtree Nature Center Trails | **Link** |   | paved
2903 | Crabtree Nature Center Trails | **Black Oak** |   | paved
2898 | Crabtree Nature Center Trails | **Sag Trail** | orange | unpaved
2905 | Crabtree Nature Center Trails | Bur Edge Trail | red | unpaved
2906 | Crabtree Nature Center Trails | Bur Edge Trail | red | unpaved
2907 | Crabtree Nature Center Trails | Bur Edge Trail | red | unpaved
2908 | Crabtree Nature Center Trails | Bur Edge Trail | red | unpaved
2910 | Crabtree Nature Center Trails | Bur Edge Trail | red | unpaved
2923 | Crabtree Nature Center Trails | Giant's Hollow Trail | blue | unpaved
2924 | Crabtree Nature Center Trails | Phantom Prairie Trail | purple | unpaved
2927 | Crabtree Nature Center Trails | Phantom Prairie Trail | purple | unpaved
2928 | Crabtree Nature Center Trails | Bur Edge Trail | red | unpaved
2931 | Crabtree Nature Center Trails | Bur Edge Trail | red | unpaved
2934 | Crabtree Nature Center Trails | Phantom Prairie Trail | purple | unpaved
2935 | Crabtree Nature Center Trails | Bur Edge Trail | red | unpaved
2937 | Crabtree Nature Center Trails | Phantom Prairie Trail | purple | unpaved
2939 | Crabtree Nature Center Trails | Phantom Prairie Trail | purple | unpaved
3052 | Crabtree Nature Center Trails |   |   | paved
3053 | Crabtree Nature Center Trails |   |   | paved
3054 | Crabtree Nature Center Trails |   |   | paved
3063 | Crabtree Nature Center Trails |   |   | paved
3013 | Crabtree Nature Center Trails |   |   | paved

## Little Red

- [ ] Segments 3045, 3046, 3048 are named "Grove Portage Trail" from River Trail. I think this is part of the Accessible Trail (see next)
- [ ] Can we name the red paved segments "Accessible Garden & Trail"
- [ ] Segment 2992 doesn't have a trail_type or trail_color
- [ ] Should segment 2955 be "Farm Pond Trail"?

trail_info_id | trail_subsystem | trail_name | trail_color | trail_type
-- | -- | -- | -- | --
2926 | Little Red Schoolhouse Nature Center Trails | White Oak | red | paved
2887 | Little Red Schoolhouse Nature Center Trails | White Oak | red | paved
2936 | Little Red Schoolhouse Nature Center Trails | Farm Pond Trail | red | unpaved
2955 | Little Red Schoolhouse Nature Center Trails | | red | unpaved
2961 | Little Red Schoolhouse Nature Center Trails | Black Oak Trail | blue | unpaved
2992 | Little Red Schoolhouse Nature Center Trails | White Oak |  
2993 | Little Red Schoolhouse Nature Center Trails | Farm Pond Trail | red | unpaved
2994 | Little Red Schoolhouse Nature Center Trails | Farm Pond Trail | red | unpaved
3014 | Little Red Schoolhouse Nature Center Trails | Black Oak Trail | blue | unpaved
3030 | Little Red Schoolhouse Nature Center Trails | White Oak Trail | green | unpaved
3031 | Little Red Schoolhouse Nature Center Trails | | red | paved
3032 | Little Red Schoolhouse Nature Center Trails | White Oak Trail | green | unpaved
3033 | Little Red Schoolhouse Nature Center Trails | | red | paved
3038 | Little Red Schoolhouse Nature Center Trails | | red | paved
3040 | Little Red Schoolhouse Nature Center Trails | | red | paved
3041 | Little Red Schoolhouse Nature Center Trails | | red | paved
3042 | Little Red Schoolhouse Nature Center Trails | | red | paved
3045 | Little Red Schoolhouse Nature Center Trails | **Grove Portage Trail** | red | paved
3046 | Little Red Schoolhouse Nature Center Trails | **Grove Portage Trail** | red | paved
3048 | Little Red Schoolhouse Nature Center Trails | **Grove Portage Trail** | red | paved
3020 | Little Red Schoolhouse Nature Center Trails | | red | paved

## River Trail
- [ ] Not sure what's going on here, looks like most of the names are from Sagawau & Sand Ridge. Some also missing trail_name and trail_color

trail_info_id | trail_subsystem | trail_name | trail_color | trail_type
-- | -- | -- | -- | --
457 | River Trail Nature Center Trails |   |   | unpaved
1040 | River Trail Nature Center Trails |   | black | unpaved
1911 | River Trail Nature Center Trails |   |   | unpaved
1052 | River Trail Nature Center Trails |   | yellow | unpaved
2900 | River Trail Nature Center Trails | Sag Trail |   | unpaved
2901 | River Trail Nature Center Trails |   |   | unpaved
2991 | River Trail Nature Center Trails |   |   | unpaved
2929 | River Trail Nature Center Trails |   | orange | paved
2952 | River Trail Nature Center Trails | Pines & Dogwood Trail | orange | paved
2953 | River Trail Nature Center Trails |   | orange | paved
2979 | River Trail Nature Center Trails |   | orange | paved
2980 | River Trail Nature Center Trails | Quarry Trail | orange | paved
2954 | River Trail Nature Center Trails | Sag Trail | orange | paved
2981 | River Trail Nature Center Trails | Sag Trail |   | unpaved
3025 | River Trail Nature Center Trails | Sag Trail | orange | paved
3026 | River Trail Nature Center Trails |   | orange | paved
3027 | River Trail Nature Center Trails |   |   | unpaved
2982 | River Trail Nature Center Trails | Green Bay Trail | | unpaved
2983 | River Trail Nature Center Trails |   |   | unpaved
2947 | River Trail Nature Center Trails | Pines & Dogwood Trail | orange | paved
2948 | River Trail Nature Center Trails |   | orange | paved
3028 | River Trail Nature Center Trails |   |   | unpaved
2956 | River Trail Nature Center Trails | Pines & Dogwood Trail | orange | paved
2957 | River Trail Nature Center Trails |   |   | unpaved
2958 | River Trail Nature Center Trails |   | orange | paved
2959 | River Trail Nature Center Trails | Quarry Trail | orange | paved
2960 | River Trail Nature Center Trails | Sag Trail | orange | paved
2984 | River Trail Nature Center Trails |   | orange | paved
2985 | River Trail Nature Center Trails | Quarry Trail | orange | paved
2986 | River Trail Nature Center Trails |   | orange | paved
2987 | River Trail Nature Center Trails | Sag Trail | orange | paved
458 | River Trail Nature Center Trails |   |   | unpaved
2949 | River Trail Nature Center Trails |   |   | unpaved
2481 | River Trail Nature Center Trails |   | orange | paved
2618 | River Trail Nature Center Trails |   | black | unpaved
2376 | River Trail Nature Center Trails |   | yellow | paved

## Sagawau
- [ ] Segements 2997, 2919, 2888 don't have trail_name or trail_color

trail_info_id | trail_subsystem | trail_name | trail_color | trail_type
-- | -- | -- | -- | --
2897 | Sagawau Environmental Learning Center Trails | Ridge Run Trail | blue | unpaved
2899 | Sagawau Environmental Learning Center Trails | Sag Trail | green | unpaved
2916 | Sagawau Environmental Learning Center Trails | Sag Trail | green | unpaved
2917 | Sagawau Environmental Learning Center Trails | Sag Trail | green | unpaved
2997 | Sagawau Environmental Learning Center Trails | | | unpaved
2919 | Sagawau Environmental Learning Center Trails | | | unpaved
2920 | Sagawau Environmental Learning Center Trails | Sag Trail | green | unpaved
2921 | Sagawau Environmental Learning Center Trails | Sag Trail | green | unpaved
3001 | Sagawau Environmental Learning Center Trails | Ridge Run Trail | blue | unpaved
2941 | Sagawau Environmental Learning Center Trails | Ridge Run Trail | blue | unpaved
2943 | Sagawau Environmental Learning Center Trails | Ridge Run Trail | blue | unpaved
2944 | Sagawau Environmental Learning Center Trails | Sag Trail | green | unpaved
2964 | Sagawau Environmental Learning Center Trails | Sag Trail | green | unpaved
2965 | Sagawau Environmental Learning Center Trails | Quarry Trail | red | unpaved
2966 | Sagawau Environmental Learning Center Trails | Quarry Trail | red | unpaved
2967 | Sagawau Environmental Learning Center Trails | Quarry Trail | red | unpaved
2969 | Sagawau Environmental Learning Center Trails | Sag Trail | green | unpaved
2970 | Sagawau Environmental Learning Center Trails | Sag Trail | green | unpaved
2974 | Sagawau Environmental Learning Center Trails | Sag Trail | green | unpaved
3003 | Sagawau Environmental Learning Center Trails | Sag Trail | green | unpaved
2946 | Sagawau Environmental Learning Center Trails | Sag Trail | green | unpaved
3004 | Sagawau Environmental Learning Center Trails | Sag Trail | green | unpaved
2888 | Sagawau Environmental Learning Center Trails | | | unpaved
2977 | Sagawau Environmental Learning Center Trails | Prairie Loop | purple | unpaved
3006 | Sagawau Environmental Learning Center Trails | Prairie Loop | purple | unpaved
3007 | Sagawau Environmental Learning Center Trails | Prairie Loop | purple | unpaved
2978 | Sagawau Environmental Learning Center Trails | Prairie Loop | purple | unpaved
2951 | Sagawau Environmental Learning Center Trails | Quarry Trail | yellow | unpaved
3091 | Sagawau Environmental Learning Center Trails | Quarry Trail | red | unpaved

## Sand Ridge
- [ ] Does it make sense for 3094 (assuming this is paved by the building) to not be named as part of the Redwing Trail so we aren't mixing paved/unpaved? Should all the paved segments around the building share the same color and have no name?

trail_info_id | trail_subsystem | trail_name | trail_color | trail_type
-- | -- | -- | -- | --
3050 | Sand Ridge Nature Center Trails |   | green | paved
3056 | Sand Ridge Nature Center Trails | Redwing Trail | blue | unpaved
2988 | Sand Ridge Nature Center Trails | Pines Trail | green | unpaved
2989 | Sand Ridge Nature Center Trails |   | green | paved
3057 | Sand Ridge Nature Center Trails | Pines Trail | green | unpaved
3062 | Sand Ridge Nature Center Trails | Dogwood Trail | purple | unpaved
3058 | Sand Ridge Nature Center Trails | Dogwood Trail | purple | unpaved
3059 | Sand Ridge Nature Center Trails | Dogwood Trail | purple | unpaved
2889 | Sand Ridge Nature Center Trails | Dogwood Trail | purple | unpaved
3012 | Sand Ridge Nature Center Trails | Dogwood Trail | purple | unpaved
3051 | Sand Ridge Nature Center Trails | Dogwood Trail | purple | unpaved
3060 | Sand Ridge Nature Center Trails | Redwing Trail | blue | unpaved
3055 | Sand Ridge Nature Center Trails | Lost Beach Trail | red | unpaved
3061 | Sand Ridge Nature Center Trails | Lost Beach Trail | red | unpaved
3092 | Sand Ridge Nature Center Trails | Redwing Trail | blue | unpaved
3093 | Sand Ridge Nature Center Trails | Redwing Trail | blue | unpaved
3094 | Sand Ridge Nature Center Trails | Redwing Trail | blue | paved

**Comment by glw** [comment]
submitting new data.
