### ISSUE TITLE
Data issues - April 14

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#164]
- [x] Add Thatcher trailhead with connection to Trailside trails - https://github.com/fpdcc/webmap_data_updates/issues/159#issuecomment-482992421
- [x] Trailside Museum of Natural History Trails fixes
- Red Paved - hiking, no dogs  _(remove biking & cross-country skiing)_
- All primitive - hiking, **dog_leash** _(remove no dogs)_
- [x] Crabtree Nature Center Trails fixes
- All trails - hiking, no dogs _(remove biking & cross-country skiing)_
- [x] River Trail Nature Center Trails fixes
- All trails - hiking, no dogs _(remove biking & cross-country skiing)_
- Can we make this just Orange paved like the rest of the segment? Is the purple paved a mistake? can it be orange paved too?
- In trails_desc, hours2 = 8 am - 4 pm
![Screen Shot 2019-04-14 at 10 08 54 AM](https://user-images.githubusercontent.com/7032169/56094940-5fb3b500-5e9d-11e9-80e7-aff25c4baad4.png)
- [x] Sagawau Environmental Learning Center Trails fixes
- All trails - hiking, no dogs, cross-country skiing _(remove biking)_
- [x] Little Red Schoolhouse Nature Center Trails fixes
- All trails - hiking, no dogs _(remove biking & cross-country skiing)_
- [x] Sand Ridge Nature Center Trails fixes
- All trails - hiking, no dogs _(remove biking & cross-country skiing)_
- [x] Orland Grassland Trail System
- Red Paved Loop add dog_leash
- [x] Add **dog_leash** back to trail segments that are completely within Nature Preserves (these are allowed to have dogs)
Example:
![Screen Shot 2019-04-14 at 10 22 04 AM](https://user-images.githubusercontent.com/7032169/56095121-2e3be900-5e9f-11e9-9467-a2bee9703ac5.png)

**Comment by versatilehuman** [comment]
@glw Also this:

See Josh's note: https://github.com/fpdcc/trailsy/issues/171#issuecomment-483031910

## trails_desc

- [ ] **Sagawau Environmental Learning Center Trails** 

- trail_desc = Explore the Sagawau Environmental Learning Center grounds on four walking trails during spring, summer and fall. During winter, Sagawau's trails transform to groomed cross-country skiing trails (with no walkers allowed).

**Comment by glw** [comment]
> * [x]  River Trail Nature Center Trails fixes

> * Can we make this just Orange paved like the rest of the segment? Is the purple paved a mistake? can it be orange paved too?
>   ![Screen Shot 2019-04-14 at 10 08 54 AM](https://user-images.githubusercontent.com/7032169/56094940-5fb3b500-5e9d-11e9-80e7-aff25c4baad4.png)

Can we not show lengths in the list that are small (in this case a "street" crossing)?

**Comment by versatilehuman** [comment]
@glw Would under .1 mi work?
@shua123 Would this be OK?

**Comment by shua123** [comment]
Yeah, I can hide the length if it is under .1 mi. Would that be for the panel and the popup or just the panel?

**Comment by versatilehuman** [comment]
Panel

**Comment by shua123** [comment]
Up on staging.

**Comment by versatilehuman** [comment]
@shua123 I'm sorry, I misread this. Can we hide the entire segment from the panel? 

Also, because there is the paved segment in the middle, it splits the unpaved trail (see below). Is there any way to prevent that?

![Screen Shot 2019-04-14 at 3 38 33 PM](https://user-images.githubusercontent.com/7032169/56098892-6ce79880-5ecb-11e9-993e-381cb005f4c7.png)

**Comment by glw** [comment]
yeah I was wondering about that too. I was thinking that it may be because it had left-over direction, and segment_type values in there. Ive removed them in the latest update

**Comment by shua123** [comment]
yeah it is because of the direction and segment_type

**Comment by versatilehuman** [comment]
@glw At Sand Ridge can we make the paved trails near the Nature Center all Orange Paved like we do at River Trail? Right now the **Pines and Redwing Trails** have a paved segment that is making it confusing. The print map doesn't actually even show the paved segments, so don't think the paved being a single color should matter there.

Also these segments are visually about the same length but display very different lengths:
![Screen Shot 2019-04-14 at 3 48 28 PM](https://user-images.githubusercontent.com/7032169/56099008-301ca100-5ecd-11e9-9411-b54d77150d1e.png)

![Screen Shot 2019-04-14 at 3 47 59 PM](https://user-images.githubusercontent.com/7032169/56099009-31e66480-5ecd-11e9-9c65-4bdb4d0985d3.png)

**Comment by shua123** [comment]
> I'm sorry, I misread this. Can we hide the entire segment from the panel?

Done!

**Comment by versatilehuman** [comment]
@shua123 Looks good. Can you remove the "segments under..." language for Nature Center trails?

![Screen Shot 2019-04-14 at 3 58 30 PM](https://user-images.githubusercontent.com/7032169/56099093-40814b80-5ece-11e9-8066-90ac06deb740.png)

**Comment by shua123** [comment]
done

**Comment by glw** [comment]
Sorry what are you asking for, for Sand Ridge? you want those small paved segments to be unpaved?

**Comment by versatilehuman** [comment]
No, can we change the paved segments of the Pines and Redwing so they aren't part of those trails?

Pines Trail (Paved segment) --> Orange Paved
Redwing Trail (Paved segment) --> Orange Paved

I don't particularly care which color, I just think the way we do it at other Nature Centers where all the paved trails around the building are a single color is more clear.

Like at River Trail:

![Screen Shot 2019-04-14 at 4 32 25 PM](https://user-images.githubusercontent.com/7032169/56099455-f5b60280-5ed2-11e9-9956-7ba0351b7c28.png)

**Comment by glw** [comment]
got it. ok

**Comment by glw** [comment]
updates posted

**Comment by versatilehuman** [comment]
@glw Sorry, should have made this clear re: dogs in NPs above...

All the Orland Grassland primitive trails need to go back to:

hiking --> 1
dog_leash --> 0
no_dogs --> 1

**Comment by versatilehuman** [comment]
@glw I made these changes on staging and uploaded a new trails.csv to GitHub so we could move to production. We just need to remember to make these on your end.

**Comment by glw** [comment]
updated
