### ISSUE TITLE
Bike Rental changes for June 2019

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#168]
Remove bike rental from all of these:

poi_info_id | name
-- | --
250 | Bemis Woods-South
269 | Blue Star Memorial Woods
138 | Bremen Grove
247 | Brezina Woods
282 | Bunker Hill
192 | Camp Dan Beard
194 | Carl R. Hansen Woods
254 | Cermak Woods
268 | Erickson Woods
288 | Forest Glen Woods
160 | Glenwood Woods-North
153 | Green Lake Woods
166 | Joe Orr Woods
277 | Linne Woods
280 | Miami Woods
305 | Midlothian Reservoir
237 | Miller Meadow-South
379 | Orland Grassland Land and Water Reserve
132 | Rubio Woods
168 | Sauk Trail Woods-Central
112 | Teason's Woods
52 | Thaddeus S. "Ted" Lechowicz Woods
267 | Tower Road Boat Launch
262 | Turnbull Woods
246 | Twenty-Sixth Street Woods-West
141 | Whistler Woods

**Comment by versatilehuman** [comment]
My bad, need to remove these activities too:

activities_id | poi_info_id | aname
-- | -- | --
7 | 269 | Blue Star Memorial Woods Bike Rental
8 | 280 | Miami Woods Bike Rental
1103 | 250 | Bemis Woods South Bike Rental
1105 | 138 | Bremen Grove Bike Rental
1106 | 247 | Brezina Woods Bike Rental
1108 | 282 | Bunker Hill Bike Rental
1112 | 192 | Camp Dan Beard Bike Rental
1116 | 194 | Carl R. Hansen Woods Bike Rental
1118 | 254 | Cermak Woods Bike Rental
1122 | 268 | Erickson Woods Bike Rental
1123 | 288 | Forest Glen Woods Bike Rental
1124 | 160 | Glenwood Woods North Bike Rental
1125 | 153 | Green Lake Woods Bike Rental
1126 | 166 | Joe Orr Woods Bike Rental
1130 | 277 | Linne Woods Bike Rental
1131 | 305 | Midlothian Reservoir Bike Rental
1132 | 237 | Miller Meadow South Bike Rental
1133 | 379 | Orland Grassland Bike Rental
1134 | 132 | Rubio Woods Bike Rental
1136 | 168 | Sauk Trail Woods-Central Bike Rental
1137 | 112 | Teason's Woods Bike Rental
1138 | 52 | Thaddeus S. "Ted" Lechowicz Woods Bike Rental
1139 | 262 | Turnbull Woods Bike Rental
1140 | 246 | Twenty-Sixth Street Woods West Bike Rental
1142 | 141 | Whistler Woods Bike Rental

**Comment by versatilehuman** [comment]
Still need to remove these in the poi_desc table

## poi_desc
Remove special_description and special_link from all of these:

poi_info_id | name|special_description|special_link
-- | -- | -- | --
250 | Bemis Woods-South|View bike  rental options | https://gohopr.com/chicagoland/
269 | Blue Star Memorial Woods|View bike  rental options | https://gohopr.com/chicagoland/
138 | Bremen Grove|View bike  rental options | https://gohopr.com/chicagoland/
247 | Brezina Woods|View bike  rental options | https://gohopr.com/chicagoland/
282 | Bunker Hill|View bike  rental options | https://gohopr.com/chicagoland/
192 | Camp Dan Beard|View bike  rental options | https://gohopr.com/chicagoland/
194 | Carl R. Hansen Woods|View bike  rental options | https://gohopr.com/chicagoland/
254 | Cermak Woods|View bike  rental options | https://gohopr.com/chicagoland/
268 | Erickson Woods|View bike  rental options | https://gohopr.com/chicagoland/
288 | Forest Glen Woods|View bike  rental options | https://gohopr.com/chicagoland/
160 | Glenwood Woods-North|View bike  rental options | https://gohopr.com/chicagoland/
153 | Green Lake Woods|View bike  rental options | https://gohopr.com/chicagoland/
166 | Joe Orr Woods|View bike  rental options | https://gohopr.com/chicagoland/
277 | Linne Woods|View bike  rental options | https://gohopr.com/chicagoland/
280 | Miami Woods|View bike  rental options | https://gohopr.com/chicagoland/
305 | Midlothian Reservoir|View bike  rental options | https://gohopr.com/chicagoland/
237 | Miller Meadow-South|View bike  rental options | https://gohopr.com/chicagoland/
379 | Orland Grassland Land and Water Reserve|View bike  rental options | https://gohopr.com/chicagoland/
132 | Rubio Woods|View bike  rental options | https://gohopr.com/chicagoland/
168 | Sauk Trail Woods-Central|View bike  rental options | https://gohopr.com/chicagoland/
112 | Teason's Woods|View bike  rental options | https://gohopr.com/chicagoland/
52 | Thaddeus S. "Ted" Lechowicz Woods|View bike  rental options | https://gohopr.com/chicagoland/
267 | Tower Road Boat Launch|View bike  rental options | https://gohopr.com/chicagoland/
262 | Turnbull Woods|View bike  rental options | https://gohopr.com/chicagoland/
246 | Twenty-Sixth Street Woods-West|View bike  rental options | https://gohopr.com/chicagoland/
141 | Whistler Woods|View bike  rental options | https://gohopr.com/chicagoland/

**Comment by glw** [comment]
Only changed values where Poi_info_id was (69,247,282,194,268,288,160,153,166,277,280,305,379,132,168,112,52,267,262,246,141) the other 4 or 5 actually contained things other than what you listed above. So I assumed it had been updated in a separate issue.
