### ISSUE TITLE
Cummings Square "trails"

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#172]
@glw  Not sure how I missed this. Can we remove? They seem to be labelled strangely as well:

![image](https://user-images.githubusercontent.com/7032169/60354707-71800100-9992-11e9-86f0-e997120d3e92.png)

![image](https://user-images.githubusercontent.com/7032169/60354720-793fa580-9992-11e9-9a94-423fbe4529de.png)

**Comment by glw** [comment]
weird. ill look into this.
