### ISSUE TITLE
Figure out GHQ/Cummings Square shared parking entrance solution

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#183]
Clustering or some other function is splitting these in a not-so-ideal way when they share a parking entrance.

Logging here, but may be more applicable to Trailsy repository depending on solution.

![image](https://user-images.githubusercontent.com/7032169/65187016-92f00680-da30-11e9-8724-ac7201cabb62.png)

**Comment by glw** [comment]
Ive updated the files to their original parking status. Should we move this issue to trailsys or close?

**Comment by versatilehuman** [comment]
Moved to Trailsy https://github.com/fpdcc/trailsy/issues/246
