### ISSUE TITLE
Trailside Museum name

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#2]
## Points_of_interest
Update to:
**Name** = Trailside Museum of Natural History
**Alt_name** = Hal Tyrell Trailside Museum

![image](https://cloud.githubusercontent.com/assets/7032169/25011201/3252f7de-2032-11e7-8ce4-fb612af5d4a6.png)

## Activities
Update to:
**Aname** = Trailside Museum of Natural History

![image](https://cloud.githubusercontent.com/assets/7032169/25011309/88fdcd48-2032-11e7-9cc0-a202f4842a4e.png)

**Comment by glw** [comment]
Am I not seeing the error? I cant see what is wrong with the orignal Name vs the new Name, for 'Trailside Museum of Natural History'.
