### ISSUE TITLE
Remove Tower Road Boat Launch Bike Rental Activity

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#201]
Remove the highlighted activity:

![image](https://user-images.githubusercontent.com/7032169/72005338-fdf95f00-3212-11ea-8f6d-a52d93dea1e8.png)

**Comment by glw** [comment]
@hallj89 to go to the ```poi_info``` table find this row by its ```poi_info_id```. Make a note of the ```nameid``` and ```pointsofinterest_id```. Then go ahead and delete the row in the ```poi_info``` table. Then go to the geometry table and delete by ```poinstofinterest_id```. Then go to ```names``` table and remove the name by ```nameid```. Then go to ```poi_amenity``` table and see if there is and row for this activity (find by ```poi_info_id```).

**Comment by versatilehuman** [comment]
@hallj89 @glw Closing this issue, we need to remove all bike rentals. See superseding #213
