### ISSUE TITLE
Special Description / Special Link

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#214]
Keep these columns, but make all values blank. 

## poi_desc
- special_description
 - special_link

See: https://github.com/fpdcc/trailsy/issues/255

We can remove these columns later after trailsy updates.

**Comment by glw** [comment]
should the columns be removed from the webmap data csv?

**Comment by versatilehuman** [comment]
Not yet. I want to wait until we make the updates to the web app before removing completely.
