### ISSUE TITLE
Basemap: Add Bergman Slough Land and Water Reserve and Elizabeth Conkey Woods Nature Preserve

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#229]
Update Nature Preserve basemap.

**Comment by jim-z** [comment]
Also add recent nature preserve additions at Wampum Lake and Harms (data already updated in quercus)

**Comment by versatilehuman** [comment]
Looks Like Harms and Wampum were updated here already: https://github.com/fpdcc/webmap_data_updates/blob/master/basemap/FPCC-basemap-nature-preserves.geojson

Just need to get them all up on the production map once Bergman and Conkey are done.
