### ISSUE TITLE
Update Major Taylor Trail Map

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#232]
## trails_desc

**Major Taylor Trail**
map_link = https://fpdcc.com/downloads/maps/trails/english/FPCC-Major-Taylor-Trail-Map-120920.pdf

## poi_desc

Find and replace in **map_link** column:

**Find:** 
- https://fpdcc.com/downloads/maps/trails/english/FPCC-Major-Taylor-Trail-Map-5-17.pdf

**Replace:** 
- https://fpdcc.com/downloads/maps/trails/english/FPCC-Major-Taylor-Trail-Map-120920.pdf

**Comment by glw** [comment]
Im not seeing anything with the old like to the major taylor map in poi_desc.
https://fpdcc.com/downloads/maps/trails/english/FPCC-Major-Taylor-Trail-Map-5-17.pdf

**Comment by versatilehuman** [comment]
OK, yeah I think we were limiting the use of the previous map. 

In **poi_desc** want to make **map_link** = https://fpdcc.com/downloads/maps/trails/english/FPCC-Major-Taylor-Trail-Map-120920.pdf for these entrances:

- Dan Ryan Woods Visitor Center (poi_info_id = 313)
- Dan Ryan Woods-91st Street (poi_info_id = 314)
- Dan Ryan Woods-Central (poi_info_id = 193)
- Dan Ryan Woods-East (poi_info_id = 312)
- Dan Ryan Woods-North (poi_info_id = 311)
- Dan Ryan Woods-South (poi_info_id = 13)
- Whistler Woods (poi_info_id = 141)
- Kickapoo Woods (poi_info_id = 145)
- Dixmoor Playfield (poi_info_id = 20)
- Calumet Woods (poi_info_id = 144)
- Little Calumet Boat Launch (poi_info_id = 143)
