### ISSUE TITLE
Remove pavement and second entrance at Dam No. 4 East

### ISSUE THREAD

**Issue by jim-z** [fpdcc/webmap_data_updates#235]
Part of parking lot was removed 2019.  See below:

![damno4_aerial](https://user-images.githubusercontent.com/11774880/102415075-2c53f280-3fbd-11eb-9e18-346ceb45394f.JPG)

![image](https://user-images.githubusercontent.com/11774880/102415231-70df8e00-3fbd-11eb-8101-6a7e85e1019b.png)

**Comment by versatilehuman** [comment]
This is a duplicate, closed March 2020: https://github.com/fpdcc/webmap_data_updates/issues/176

Confirmed with latest here: https://github.com/fpdcc/webmap_data_updates/tree/master/basemap
