### ISSUE TITLE
accessible column for activities table

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#242]
## activities
- [x] Set new accessible column to be included in activities table export
- [x] Add/update activities per below:

### Add these

activities_id | aname | atype | parking_info_id | poi_info_id | accessible | geom
-- | -- | -- | -- | -- | -- | --
? | Busse Lake Boating Center Accessible Canoe Landing | canoe landing | 313 | 189 | 1 | approx 42.024431, -88.015902
? | Camp Bullfrog Lake Accessible Canoe Landing | canoe landing | 334 | 100 | 1 | approx 41.709986, -87.901663
? | Camp Bullfrog Lake Accessible Fishing Area | accessible fishing | 334 | 100 | 1 | approx 41.708551, -87.902000
? | Beaubien Woods Accessible Fishing Area | accessible fishing | 321 | 147 | 1 | approx 41.649638, -87.584098
? | Busse Lake Beisner Road Access Accessible Fishing Area | accessible fishing | 144 | 187 | 1 | approx 42.018880, -88.012273
? | Busse Forest-West Accessible Fishing Area | accessible fishing | 314 | 190 | 1 | approx 42.034313, -88.014456
? | Busse Forest Main Dam Accessible Fishing Area | accessible fishing | 145 | 186 | 1 | approx 42.019003, -87.999933
? | Maple Lake Boating Center Accessible Fishing Area | accessible fishing | 177 | 378 | 1 | approx 41.712821, -87.894380
? | Oak Forest Heritage Preserve-West Accessible Fishing Area | accessible fishing | 350 | 1078 | 1 | approx 41.598666, -87.727391
? | Saganashkee Slough-East Accessible Fishing Area | accessible fishing | 256 | 323 | 1 | approx 41.689513, -87.875184
? | Tower Road Boat Launch Accessible Fishing Area | accessible fishing | 233 | 267 | 1 | **approx 42.113807, -87.774880

### Update these (aname/accessible)

activities_id | aname | atype | parking_info_id | poi_info_id | accessible 
-- | -- | -- | -- | -- | -- 
1000 | **Tower Road Accessible Boat Launch** | boat launch | 233 | 267 | **1**
1047 | **Saganashkee Slough Accessible Boat Launch** | boat launch | 261 | 324 | **1**

### Move this

**Tower Road Accessible Boat Launch (activities_id = 1000) should be moved to approx 42.113509, -87.774719. That location better reflects that actual location of the launch and won't overlap with new accessible fishing area.

**Comment by versatilehuman** [comment]
@glw The accessible column got over applied in the activities table. Need to make these all accessible = 0
 
activities_id | atype | aname | accessible
-- | -- | -- | --
14 | recreational waterbody | Flatfoot Lake | 0
24 | recreational waterbody | Deer Grove Lake | 0
33 | recreational waterbody | Skokie Lagoons | 0
36 | recreational waterbody | Schiller Pond | 0
45 | recreational waterbody | Cermak Quarry | 0
66 | recreational waterbody | Busse Lake North Pool | 0
69 | recreational waterbody | Busse Lake South Pool | 0
72 | recreational waterbody | Busse Lake Main Pool | 0
94 | recreational waterbody | Maple Lake | 0
100 | camp | Camp Bullfrog Lake | 0
113 | camp | Camp Shabbona Woods | 0
136 | camp | Camp Sullivan | 0
179 | camp | Camp Reinberg | 0
192 | camp | Camp Dan Beard | 0
803 | trailhead | Blue Star Memorial Woods | 0
806 | trailhead | Busse Lake Boating Center | 0
815 | trailhead | Busse Forest-West | 0
817 | trailhead | Palos Park Woods-North | 0
819 | trailhead | Forest Glen Woods | 0
821 | boat rental | Camp Bullfrog Lake Boat Rental | 0
822 | trailhead | Irene C. Hernandez | 0
826 | dog park | Miller Meadow Dog Park | 0
835 | trailhead | Allison Woods | 0
836 | dog park | Bremen Grove Dog Park | 0
843 | trailhead | Maple Lake Boating Center | 0
845 | trailhead | Bunker Hill | 0
846 | trailhead | Miller Meadow-South | 0
851 | trailhead | Harms Woods-North | 0
865 | trailhead | Rubio Woods | 0
866 | trailhead | Schiller Woods-West | 0
870 | trailhead | Plum Creek Meadow | 0
874 | trailhead | Dam No. 4 Woods-East | 0
882 | trailhead | LaBagh Woods | 0
883 | trailhead | Dan Ryan Woods-Central | 0
888 | trailhead | Bremen Grove | 0
892 | trailhead | Barrington Road Pond | 0
900 | trailhead | Saganashkee Slough-East | 0
904 | trailhead | Bunker Hill | 0
910 | trailhead | Busse Lake Beisner Road Access | 0
911 | trailhead | Busse Forest Main Dam | 0
918 | trailhead | Brookfield Woods | 0
919 | trailhead | Brezina Woods | 0
921 | trailhead | Arrowhead Lake | 0
933 | trailhead | Deer Grove | 0
934 | trailhead | Deer Grove | 0
936 | trailhead | Bemis Woods-South | 0
940 | sledding | Deer Grove Sledding Hill | 0
945 | zip line | Go Ape Zipline & Adventure Park | 0
955 | sledding | Schiller Woods-East Sledding Hill | 0
966 | trailhead | Midlothian Meadows | 0
973 | trailhead | Sweet Woods | 0
974 | trailhead | Vollmer Road Grove | 0
977 | trailhead | Tower Road ~~Accessible~~ Boat Launch | 0
985 | trailhead | Camp Bullfrog Lake | 0
990 | trailhead | Sunset Bridge Meadow | 0
999 | boat launch | Busse Lake Boat Launch | 0
1002 | boat launch | Busse Lake South Boat Launch | 0
1006 | canoe landing | Allison Woods Canoe Landing | 0
1024 | recreational waterbody | Arrowhead Lake | 0
1050 | recreational waterbody | Barrington Road Pond | 0
1051 | boating center | Busse Lake Boating Center | 0
1052 | boating center | Maple Lake Boating Center | 0
1067 | trailhead | Camp Reinberg | 0
1069 | trailhead | Schiller Woods-East | 0
1070 | trailhead | Bemis Woods-South | 0
1071 | trailhead | Cermak Woods | 0
1079 | trailhead | Oak Forest Heritage Preserve-West | 0
1098 | canoe landing | Maywood Grove Canoe Landing | 0
1099 | recreational waterbody | Pogie Lake | 0

And need to fix this name:
activities_id | atype | aname | accessible
-- | -- | -- | --
977 | trailhead | Tower Road ~~Accessible~~ Boat Launch | 0

**Comment by glw** [comment]
how about for activity 977, aname = Tower Road?

**Comment by versatilehuman** [comment]
It should be aname = Tower Road Boat Launch 

and it'll appear like this:

![image](https://user-images.githubusercontent.com/7032169/125130141-18d9b780-e0c6-11eb-837f-5c0cd9b24692.png)

**Comment by glw** [comment]
@versatilehuman there was an error in the code for creating the activities view (table). that's been updated and is now reflecting the correct accessible activities. 

That brings up a some changes in column names that I would like to introduce to the activities table to make it line up more with the POI table. These would only affect the activities table. I can outline what I would like to change in a separate issue. 
CC: @shua123
