### ISSUE TITLE
Update trails around Sand Ridge

### ISSUE THREAD

**Issue by jim-z** [fpdcc/webmap_data_updates#252]
Spur to nature center should change from red to black, two new nature center trails to camp, new spur (blue) to camp entrance along Torrance.  Trail on east side of Torrance (currently purple in webmap) built/managed by municipality...not sure how we want to represent that.

![image](https://user-images.githubusercontent.com/11774880/112689050-becf2200-8e47-11eb-8cd7-d20558e82051.png)

**Comment by versatilehuman** [comment]
@glw From left to right:

- Remove red nubbin
- Rename Black Paved (remove "spur" segment_type)
- Good
- Rename Brown Paved **_Spur_** (add "spur" segment_type)

If we aren't going to use different colors for the fishing spurs (which makes sense), then I think we just include them as part of the black paved trail and don't use "spur".

![image](https://user-images.githubusercontent.com/7032169/124297142-5ebfda00-db20-11eb-8876-770a1cd9b122.png)


Is there a little bitty spur at 159th & Paxton? Didn't make it on to the web map (if you add, same deal here, just Black Paved):

![image](https://user-images.githubusercontent.com/7032169/124297620-ddb51280-db20-11eb-91b4-e15cb1a35f48.png)

![image](https://user-images.githubusercontent.com/7032169/124297646-e574b700-db20-11eb-8fd3-2e3930edd7c0.png)

**Comment by glw** [comment]
yeah im not sure if they will end up getting different color or not. for the moment they dont.
