### ISSUE TITLE
Add Des Plaines Trail Bryn Mawr Bridge

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#265]
@glw Ribbon cutting is 7/17 if we can update before then.

![image](https://user-images.githubusercontent.com/7032169/125102812-4fe9a200-e0a1-11eb-864e-18749f9cba4b.png)

**Comment by glw** [comment]
Looks like i had already completed this but forgot to close out.

**Comment by versatilehuman** [comment]
@glw Are these all the same segment (same length, adding up to 1.2mi). Can you investigate and either change color for the spur, or not list this as a spur? Yellow Unpaved Spur is too confusing with the main Yellow Unpaved. 

![image](https://user-images.githubusercontent.com/7032169/126196721-730e864d-360a-4276-9dc9-6bcb40e39e53.png)

trail_color | trail_surface | trail_type | trail_difficulty | regional_trail_name | trail_desc | alt_name | cambr_name | on_street | crossing_type | length_mi | off_fpdcc | web_trail | length_ft | segment_type | direction | width | hiking | biking | cross_country | equestrian | dog_leash | no_dogs | geom
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
yellow | unknown | unpaved | easy | Des Plaines River Trail |   | no | none | 0.4 | no | yes | 2122.56 | spur |   | 0 | 1 | 1 | 1 | 1 | 1 | 0 | 0102000020E610000002000000DB243461BFF655C00582E9B888FD4440DF4782A4C4F655C05547C24988FD4440
yellow | unknown | unpaved | easy | Des Plaines River Trail |   | no | bridge | 0.4 | no | yes | 2122.56 | spur |   | 0 | 1 | 1 | 1 | 1 | 1 | 0 | 0102000020E610000002000000DF4782A4C4F655C05547C24988FD4440E8EABBC0CDF655C0C8C1DA9B87FD4440
yellow | unknown | unpaved | easy | Des Plaines River Trail |   | no | none | 0.4 | no | yes | 2122.56 | spur |   | 0 | 1 | 1 | 1 | 1 | 1 | 0 | 0102000020E610000002000000E8EABBC0CDF655C0C8C1DA9B87FD4440B843E9DAD9F655C07D910A6587FD4440



</body>

</html>

**Comment by glw** [comment]
updated to green (central)
