### ISSUE TITLE
Remove Accessible Indoor Bathroom at Busse-Forest North

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#291]
## points_of_interest
**Busse Forest-North** (poi_info_id=184)

- bathroom_building_winter = 0
- bathroom_building_summer = 0
- bathroom_building_ada = 0

**Comment by glw** [comment]
Im going to leave the data alone in our picnicgroves table (shelter_to_bathroom, bathroom_type) so that we dont loose that info later when the bathroom comes back online. And hopefully that doesnt impact anything negatively.

**Comment by alxstockdale** [comment]
Agreed. Let's leave those as-is.

**Comment by alxstockdale** [comment]
Correction: The bathroom building for summer (non-ADA) shouldn't have been modified to zero. Obviously not a rush on this one but wanted to capture this for later and reopen it.

## points_of_interest
**Busse Forest-North** (poi_info_id=184)

- bathroom_building_summer = 1
