### ISSUE TITLE
Update portable bathroom at Grassy Ridge Meadow

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#297]
## points_of_interest
**Grassy Ridge Meadow** (poi_info_id=183)

- bathroom_portable_winter = 1

**Comment by glw** [comment]
Since this is now open in winter, does this text need to be updated?
![image](https://user-images.githubusercontent.com/556205/212437184-a9951cf8-1510-4764-ad3e-ee7260b499f0.png)

**Comment by alxstockdale** [comment]
The text should automatically update (disappear in this case along with the asterisk next to the bathroom icon) once bathroom_portable_winter changes to 1.
