### ISSUE TITLE
Update Quarry Trail activities

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#305]
### trails

**Quarry Trail** (trail_subsystem_id=28)

- hiking = 0

**Comment by glw** [comment]
Sorry @alxstockdale which trail specifically is this one?

**Comment by alxstockdale** [comment]
@glw I guess that would've been helpful! 

Here you go: https://map.fpdcc.com/#/?trail=Sagawau+Environmental+Learning+Center+Trails

**Comment by alxstockdale** [comment]
@jim-z This is a weird case, where it's only used primarily for cross country skiing, so they'd like to remove the hiking icon for it. Trail will remain open though, but updating hiking to 0 will only remove that icon.

![image](https://github.com/fpdcc/webmap_data_updates/assets/112649860/e642ae96-3223-4f0b-9627-9c4046e8d1b7)
