### ISSUE TITLE
165 Algonquin updates

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#306]
### points_of_interest

**165 Algonquin** (poi_info_id=1176)

- name = Spring Creek Parking -> 165 Algonquin
- web_street_addr = Algonquin Rd, west of Old Sutton Rd
- web_muni_addr = Barrington, IL 60010
- no_parking = 0
- hiking = 1
- bathroom_portable_summer = 1
- bathroom_portable_winter = 1
- bathroom_portable_ada = 1

### poi_desc

**165 Algonquin** (create poi_desc_id)

- poi_info_id = 1176
- hours1 = Sunrise to Sunset
- season1 = Year-round
- map_link = https://fpdcc.com/downloads/maps/zones/english/FPCC-Northwest-Zone-Map-10-15.pdf
- map_link_spanish = https://fpdcc.com/downloads/maps/zones/spanish/FPCC-Northwest-Zone-Map-SPANISH-10-15.pdf
- web_link = https://fpdcc.com/places/locations/165-algonquin/

**Comment by alxstockdale** [comment]
Minor update to name for consistency purposes:

### points_of_interest

**165 Algonquin Road** (poi_info_id=1176)

- name = 165 Algonquin Road

### poi_desc

**165 Algonquin Road** (poi_info_id = 1176)

- web_link = https://fpdcc.com/places/locations/165-algonquin-road/

**Comment by jim-z** [comment]
Updated in database
