### ISSUE TITLE
Poplar Creek Land and Water Reserve designation

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#311]
### points_of_interest

**Poplar Creek Land and Water Reserve**

- name = Poplar Creek Land and Water Reserve
- alt_name = Carl R. Hansen Woods
- alt2_name = Poplar Creek Prairie
- point_type = nature preserve
- web_muni_addr = Cook County, IL 60192
- maintenance_div = Northwest
- cycling = 1
- cross_country = 1
- hiking = 1
- dog_leash = 1
- ecological = 1
- nature_preserve = 1
- no_fishing = 1
- no_parking = 1
- volunteer = 1

### poi_desc

**Poplar Creek Land and Water Reserve**

- hours1 = Sunrise to Sunset
- description = Poplar Creek Land and Water Reserve, part of the larger Arthur L. Janura Preserve, is home to approximately 572-acres of reconstructed prairie, savanna, mesic woodland and streamside fen natural communities. The land has been successfully transformed into functional native ecosystems through significant investments in restoration and the efforts of volunteer groups such as the Poplar Creek Prairie Stewards, who have led management of the site since 1989.
- web_link = https://fpdcc.com/places/locations/arthur-l-janura-preserve/
- map_link = https://fpdcc.com/downloads/maps/trails/english/FPCC-Poplar-Creek-Trail-2018-010919.pdf
- map_link_spanish = https://fpdcc.com/downloads/maps/zones/spanish/FPCC-Northwest-Zone-Map-SPANISH-10-15.pdf
- vol_link = https://ec.samaritan.com/recruiter/index.php?recruiterID=1405&class=OppDetails&oppGuid={381C0592-CCF8-403F-8D95-139B01B35002}
- season1 = Year-round

**Comment by jim-z** [comment]
@alxstockdale @shua123 should we wait for this nature preserve to be added to the basemap before adding a new POI point?  @shua123 what do you need from us to update this?

**Comment by ccjoshk** [comment]
@jim-z  If you update the appropriate geojson file(s) in the basemap folder of this repo, I can copy it over to the server to update the basemap.

**Comment by alxstockdale** [comment]
@jim-z and @ccjoshk, checking in on the status of this one. We'll need to update the web map and link/carry the updates over to our website soon-ish.

**Comment by jim-z** [comment]
@ccjoshk updated nature preserve geojson added to basemap folder whenever you get a chance to update

**Comment by alxstockdale** [comment]
### points_of_interest

**Poplar Creek Land and Water Reserve** (poi_info_id=1191)

- web_muni_addr = Cook County, IL 60192
- parking_connection_id = 156
- parking_info_id = 0

### poi_desc
