### ISSUE TITLE
Add Watersmeet Woods

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#312]
### points_of_interest

**Watersmeet Woods** (poi_info_id=50)

- name = Watersmeet Woods
- web_poi = yes
- volunteer = 1
- no_parking = 1
- web_muni_addr = Cook County, IL 60093
- maintenance_div = North Branch
- point_type = activity area

**Comment by alxstockdale** [comment]
Reopening due to broken web map link on web page.

**Comment by jim-z** [comment]
updated in database
