### ISSUE TITLE
Deer Grove New Trail and Parking Lot Removal, Change Spur Color at Deer Grove East

### ISSUE THREAD

**Issue by jim-z** [fpdcc/webmap_data_updates#317]
Add new trail spur (color green) and remove portion of parking lot at Deer Grove
![image](https://github.com/fpdcc/webmap_data_updates/assets/11774880/474e3ba5-6eaf-4291-8d90-19f4661916db)

Change trail spur color to light blue at Deer Grove East
![image](https://github.com/fpdcc/webmap_data_updates/assets/11774880/e157cd5c-1e79-4d6e-badc-cf3656d3396d)

**Comment by jim-z** [comment]
Trail updates complete.  Will need to update parking lot removal through basemap.

**Comment by alxstockdale** [comment]
Awaiting basemap updates
