### ISSUE TITLE
Rename Busse Lake Boating Center

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#320]
## points_of_interest

**Busse Lake Boating Center** (poi_info_id=189)

- name = Busse Lake North Pool Accessible Fishing Area

## poi_desc

**Busse Lake Boating Center** (poi_info_id=189)

- accessibility_description = Busse Lake North Pool Accessible Fishing Area has an accessible picnic shelter (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible indoor bathroom. It also has an accessible canoe landing with accessible parking and a paved path to the landing. The surface of the landing is stable, firm and slip resistant.

**Comment by jim-z** [comment]
POI data updated.  New poi_desc entry created for Busse North Accessible Fishing Area.
