### ISSUE TITLE
Add 6101 Oak Forest Ave (Villa Santa Maria)

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#321]
### points_of_interest

**6101 Oak Forest Ave** (create poi_info_id)

- name = 6101 Oak Forest Ave
- web_street_addr = Oak Forest Ave, west of Central Ave
- web_muni_addr = Tinley Park, IL 60477
- hiking = 1
- point_type = activity area
- web_poi = yes
- maintenance_div = Tinley Creek
- latitude = TBD
- longitude = TBD

### poi_desc

**6101 Oak Forest Ave** (create poi_desc_id)

- poi_info_id = TBD
- hours1 = Sunrise to Sunset
- season1 = Year-round
- map_link = https://fpdcc.com/downloads/maps/zones/english/FPCC-Southwest-Zone-Map-022020.pdf
- map_link_spanish = https://fpdcc.com/downloads/maps/zones/spanish/FPCC-Southwest-Zone-Map-SPANISH-10-15.pdf
- web_link = https://fpdcc.com/places/locations/6101-Oak-Forest-Ave/ (currently not active)

**Comment by jim-z** [comment]
POI added to data

**Comment by alxstockdale** [comment]
**6101 Oak Forest Avenue** (poi_info_id = 1193)

- web_link = https://fpdcc.com/places/locations/6101-Oak-Forest-Avenue/

**Comment by jim-z** [comment]
Updated in database
