### ISSUE TITLE
Bluff Spring Fen Nature Preserve entrance/location updates

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#324]
See 7/24 email.

**Comment by jim-z** [comment]
POI point moved closer to parking lot area

**Comment by alxstockdale** [comment]
Weird. Bluff Spring Fen Nature Preserve is no longer listed/searchable on the web map

**Comment by jim-z** [comment]
IDs were entered incorrectly.  Fixed in database.
