### ISSUE TITLE
Paul Douglas / Grassy Ridge Meadow updates

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#325]
## poi_desc

**Grassy Ridge Meadow** (poi_info_id=183)

- description = The Grassy Ridge Meadow entrance is within the 1,800-acre Paul Douglas Preserve. With 25 miles of trails, it caters to diverse outdoor activities, from leisurely strolls to biking. The trail system includes paved and single track routes. Bird enthusiasts will delight in the vast grasslands, renewed wetlands, and a heron rookery, perfect for observing nesting species.

## trails

**Paul Douglas Trail** (trail_desc_id=20)

- description = The trail network offers diverse options, from paved paths to mountain biking routes. It's perfect for peaceful walks, invigorating hikes, and exciting biking. These trails also connect to Crabtree Trail and Nature Center.

**Comment by jim-z** [comment]
@alxstockdale there is currently a 500 character limit on the poi_desc field and 250 character limit on the trail_desc field.  Might take me some time to figure out how to increase these limits without screwing up the database.  Is it possible to make these descriptions a bit more concise for now?

**Comment by alxstockdale** [comment]
@jim-z updated

**Comment by alxstockdale** [comment]
Minor updates:

## poi_desc

**Grassy Ridge Meadow** (poi_info_id=183)

- description = The Grassy Ridge Meadow entrance is within the 1,800 acre Paul Douglas Preserve. With 25 miles of trails, it caters to diverse outdoor activities, from leisurely strolls to biking. The trail system includes paved and single track routes. Bird enthusiasts will delight in the vast grasslands, renewed wetlands and a heron rookery, perfect for observing nesting species.

## trails

**Paul Douglas Trail** (trail_desc_id=20)

- description = The trail network offers diverse options, from paved paths to mountain biking routes. It's perfect for peaceful walks, invigorating hikes and biking. These trails also connect to Crabtree Trail and Nature Center.

**Comment by jim-z** [comment]
updated in database
