### ISSUE TITLE
Add entranceway/parking to basemap for 6101 Oak Forest Avenue

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#327]
poi_info_id=1193

![image](https://github.com/fpdcc/webmap_data_updates/assets/112649860/d031bcd6-c686-4219-8363-13cab1c10768)

**Comment by jim-z** [comment]
updated in gis database

**Comment by alxstockdale** [comment]
Awaiting basemap updates

**Comment by jim-z** [comment]
Basemap updated with lot.  Still need to update parking "P" icon dataset.
