### ISSUE TITLE
Add Tan Trail at Chipilly Woods

### ISSUE THREAD

**Issue by jim-z** [fpdcc/webmap_data_updates#330]
Per email from Troy Showerman, 9/11/2024

**Comment by jim-z** [comment]
Trail added back into database.  Marked unrecognized and webmap=no until we decide if this should be made official.

**Comment by alxstockdale** [comment]
Leaving open for now.

**Comment by alxstockdale** [comment]
@jim-z Both This is likely known, but just to clarify, the blue and tan trails are both retired and can be set to webmap=no.

**Comment by jim-z** [comment]
updated in db
