### ISSUE TITLE
Update Schiller Woods-East & Schiller Woods-West grove PDF maps

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#332]
## poi_desc

**Schiller Woods-East** (poi_info_id=221)

- picnic_link = https://fpdcc.com/downloads/maps/grove/FPCC-Picnic-Map-Schiller-Woods-092523.pdf

**Schiller Woods-West** (poi_info_id=218)

- picnic_link = https://fpdcc.com/downloads/maps/grove/FPCC-Picnic-Map-Schiller-Woods-092523.pdf

**Comment by jim-z** [comment]
updated in database
