### ISSUE TITLE
Update Tampier Lake-West and Potawatomi Woods grove maps

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#334]
## poi_desc

**Tampier Lake-West** (poi_info_id=124)

- picnic_link = https://fpdcc.com/downloads/maps/grove/FPCC-Picnic-Map-Tampier-Lake-West-111523.pdf

**Potawatomi Woods** (poi_info_id=206)

- picnic_link = https://fpdcc.com/downloads/maps/grove/FPCC-Picnic-Map-Potawatomi-Woods-111523.pdf

**Comment by jim-z** [comment]
updated in db
