### ISSUE TITLE
Salt Creek Trail System map updates

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#337]
Awaiting updated PDF from GIS. See forwarded email on 11/24.

**Comment by hallj89** [comment]
[FPCC-Salt-Creek-Trail-Map-3-23.pdf](https://github.com/fpdcc/webmap_data_updates/files/13505484/FPCC-Salt-Creek-Trail-Map-3-23.pdf)

**Comment by jim-z** [comment]
@alxstockdale anything else needed here or just the PDF Jeremy already sent?

**Comment by alxstockdale** [comment]
@jim-z @hallj89 The previous version includes both an English and a Spanish version. Is it possible to get a modified Spanish version as well to update both in one go?

**Comment by hallj89** [comment]
[FPCC-Salt-Creek-Trail-Map-2-24.pdf](https://github.com/fpdcc/webmap_data_updates/files/14421965/FPCC-Salt-Creek-Trail-Map-2-24.pdf)
[FPCC-Salt-Creek-Trail-Map-Spanish-2-24.pdf](https://github.com/fpdcc/webmap_data_updates/files/14421966/FPCC-Salt-Creek-Trail-Map-Spanish-2-24.pdf)
Spanish and updated English versions

**Comment by alxstockdale** [comment]
## trails_desc

**Salt Creek Trail System**

map_link = https://fpdcc.com/downloads/maps/trails/english/FPCC-Salt-Creek-Trail-Map-2-24.pdf
map_link_spanish = https://fpdcc.com/downloads/maps/trails/spanish/FPCC-Salt-Creek-Trail-Map-Spanish-2-24.pdf

**Comment by jim-z** [comment]
links updated in db
