### ISSUE TITLE
Picnic grove map updates

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#346]
## poi_desc

**Barrington Road Pond** (poi_info_id=197)

- picnic_link = https://fpdcc.com/downloads/maps/grove/FPCC-Picnic-Map-Barrington-Road-Pond-030124.pdf

**Lansing Woods** (poi_info_id=165)

- picnic_link = https://fpdcc.com/downloads/maps/grove/FPCC-Picnic-Map-Lansing-Woods-020824.pdf

**Comment by jim-z** [comment]
updated in db
