### ISSUE TITLE
Aquatic center updates

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#350]
## poi_desc

**Cermak Family Aquatic Center** (poi_info_id=44)

- description = Cermak Family Aquatic Center in Lyons offers a fun and relaxing aquatic escape. Featuring kid-friendly zero-depth entry, a lazy river, a water playground and refreshing spray features, visitors can swim, play and unwind surrounded by nature in a family-friendly environment.
- hours1 = 
- hours2 = 

**Green Lake Family Aquatic Center** (poi_info_id=15)

- description = Green Lake Family Aquatic Center invites families to enjoy its kid-friendly features. Nestled within the Sand Ridge Campus of the Calumet Region, it boasts a zero-depth entry pool, a multi-person tube slide, a lazy river and a water playground complete with a dump bucket and spraying water features. Lounge areas surround the aquatic center, while a vast 585-acre nature-based education and recreation area awaits just beyond. Here, visitors can explore the region’s natural and cultural history through activities like swimming, hiking, biking, fishing and camping.
- hours1 = 
- hours2 =

**Whealan Pool Aquatic Center** (poi_info_id=284)

- description = Whealan Pool Aquatic Center, part of Caldwell Woods in Chicago’s historic Edgebrook neighborhood, is a go-to destination for aquatic activities. It caters to swimmers of all ages and abilities with a lap pool, zero-depth leisure pool, water playground, kiddie pool, water climbing wall and water slides. Whether you crave laps, a water aerobics class or just poolside relaxation, Whealan Pool Aquatic Center has you covered.
- hours1 = 
- hours2 =

**Comment by jim-z** [comment]
updated in db
