### ISSUE TITLE
Accessibility updates

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#351]
## points_of_interest

**Miller Meadow-North** (poi_info_id=236)

accessible = 0
accessible_shelter = 0

**Miller Meadow-South** (poi_info_id=237)

accessible = 0
accessible_shelter = 0

## poi_desc

**Miller Meadow-North** (poi_info_id=236)

accessibility_description = 

**Miller Meadow-South** (poi_info_id=237)

accessibility_description = 

**Dan Ryan Woods-Central** (poi_info_id=193)

accessibility_description = Dan Ryan Woods-Central has an accessible picnic shelter (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible indoor bathroom.

## picnicgroves

**Miller Meadow-South** (grove=5; picnicgrove_id=27)

accessible = 0
parking_to_shelter =
shelter_to_bathroom =

**Miller Meadow-South** (grove=6; picnicgrove_id=208)

accessible = 0
parking_to_shelter =
shelter_to_bathroom =

**Dan Ryan Woods-Central** (grove=5; picnicgrove_id=264)

accessible = 0
parking_to_shelter =
shelter_to_bathroom =

**Comment by jim-z** [comment]
updated in db
