### ISSUE TITLE
Camping hour updates

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#352]
## poi_desc

**Camp Bullfrog Lake** (poi_info_id=100)

- hours1 = 24 hours a day for registered campers (with campgrounds accessible from 7 am to 10 pm; quiet hours are observed from 11 pm to 7 am). Staff is available from 8 am to 4 pm.

**Camp Dan Beard** (poi_info_id=192)

- hours1 = 24 hours a day for registered campers (with campgrounds accessible from 7 am to 10 pm; quiet hours are observed from 11 pm to 7 am). Staff is available from 8 am to 4 pm.

**Camp Reinberg** (poi_info_id=179)

- hours1 = 24 hours a day for registered campers (with campgrounds accessible from 7 am to 10 pm; quiet hours are observed from 11 pm to 7 am). Staff is available from 8 am to 4 pm.

**Camp Shabbona Woods** (poi_info_id=113)

- hours1 = 24 hours a day for registered campers (with campgrounds accessible from 7 am to 10 pm; quiet hours are observed from 11 pm to 7 am). Staff is available from 8 am to 4 pm.

**Camp Sullivan** (poi_info_id=136)

- hours1 = 24 hours a day for registered campers (with campgrounds accessible from 7 am to 10 pm; quiet hours are observed from 11 pm to 7 am). Staff is available from 8 am to 4 pm.

**Comment by jim-z** [comment]
updated in db
