### ISSUE TITLE
Oak Forest Heritage Preserve description updates

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#353]
## poi_desc

**Oak Forest Heritage Preserve-East** (poi_info_id=365)

- description = Oak Forest Heritage Preserve provides opportunities to learn about this preserve's diverse cultural and historical significance while traversing a nearly 2-mile paved loop trail. The site offers healthy and restful activities such as walking, birding and wildlife watching.

**Oak Forest Heritage Preserve-West** (poi_info_id=1078)

- description = Oak Forest Heritage Preserve provides opportunities to learn about this preserve's diverse cultural and historical significance while traversing a nearly 2-mile paved loop trail. The site offers healthy and restful activities such as walking, birding and wildlife watching.

**Comment by jim-z** [comment]
updated in db
