### ISSUE TITLE
Spring portable bathroom and accessibility description updates

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#355]
## points_of_interest

**Blue Star Memorial Woods** (poi_info_id=269)

bathroom_portable_ada = 1

**Busse Forest-North** (poi_info_id=184)

bathroom_portable_ada = 1

**Camp Ground Road Woods** (poi_info_id=207)

bathroom_portable_winter = 1
bathroom_portable_ada = 1

**Eggers Grove** (poi_info_id=315)

accessible = 1
accessible_shelter = 1

**Forest Way Grove** (poi_info_id=265)

bathroom_portable_ada = 1

**Glenwood Woods-North** (poi_info_id=160)

bathroom_portable_ada = 1

**LaBagh Woods** (poi_info_id=56)

bathroom_portable_summer = 1

**Lansing Woods** (poi_info_id=165)

bathroom_portable_winter = 0

**Oak Forest Heritage Preserve-East** (poi_info_id=365)

bathroom_portable_summer = 1
bathroom_portable_winter = 1

**Plum Creek Meadow** (poi_info_id=28)

bathroom_portable_ada = 1

**Possum Hollow Woods** (poi_info_id=248)

bathroom_portable_ada = 1

**Pulaski Woods** (poi_info_id=321)

accessible = 1
accessible_shelter = 1
bathroom_portable_ada = 1

**Red Gate Woods** (poi_info_id=326)

accessible = 1
accessible_shelter = 1
bathroom_portable_ada = 1

**Sauk Trail Woods-Central** (poi_info_id=168)

accessible = 1
accessible_shelter = 1

**Schuth's Grove** (poi_info_id=238)

accessible = 1
accessible_shelter = 1

**St. Paul Woods** (poi_info_id=279)

bathroom_portable_ada = 1

**Tinley Creek Woods** (poi_info_id=176)

accessible = 1
accessible_shelter = 1
bathroom_portable_ada = 1

**Tampier Greenway Family Picnic Area** (poi_info_id=366)

bathroom_portable_ada = 0

**Tampier Lake-West** (poi_info_id=124)

bathroom_portable_ada = 1

**Wampum Lake** (poi_info_id=22)

accessible = 1
accessible_shelter = 1
bathroom_portable_ada = 1

**Wolf Road Woods** (poi_info_id=320)

accessible = 1
accessible_shelter = 1
bathroom_portable_ada = 1

## poi_desc

**Bemis Woods-South** (poi_info_id=50)

accessibility_description = Bemis Woods-South has two accessible picnic shelters (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible portable bathroom.

**Busse Lake Boating Center** (poi_info_id=189)

accessibility_description = Busse Lake Boating Center has two accessible picnic shelters (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible indoor bathroom. It also has an accessible canoe landing with accessible parking and a paved path to the landing. The surface of the landing is stable, firm and slip resistant.

**Deer Grove** (poi_info_id=180)

accessibility_description = Deer Grove has three accessible picnic shelters (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible portable bathroom.

**Eggers Grove** (poi_info_id=315)

accessibility_description = Eggers Grove has an accessible picnic shelter (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible portable bathroom.

**Midlothian Meadows** (poi_info_id=306)

accessibility_description = Midlothian Meadows has two accessible picnic shelters (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible portable bathroom.

**Pulaski Woods** (poi_info_id=321)

accessibility_description = Pulaski Woods has an accessible picnic shelter (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible portable bathroom.

**Red Gate Woods** (poi_info_id=326)

accessibility_description = Red Gate Woods has an accessible picnic shelter (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible portable bathroom.

**Sauk Trail Woods-Central** (poi_info_id=168)

accessibility_description = Sauk Trail Woods-Central has an accessible picnic shelter (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible portable bathroom.

**Schuth's Grove** (poi_info_id=238)

accessibility_description = Schuth's Grove has an accessible picnic shelter (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible portable bathroom.

**Sweet Woods** (poi_info_id=159)

accessibility_description = Sweet Woods has an accessible picnic shelter (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible portable bathroom.

**Tinley Creek Woods** (poi_info_id=176)

accessibility_description = Tinley Creek Woods has an accessible picnic shelter (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible portable bathroom.

**Wampum Lake** (poi_info_id=22)

accessibility_description = Wampum Lake has an accessible picnic shelter (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible portable bathroom.

**Comment by jim-z** [comment]
updated in db.  Awaiting confirmation on bemis south picnic grove 6 status.

**Comment by alxstockdale** [comment]
## points_of_interest

**Sauk Trail Woods-Central** (poi_info_id=168)

accessible = 1
accessible_shelter = 1

## poi_desc

**Sauk Trail Woods-Central** (poi_info_id=168)

accessibility_description = Sauk Trail Woods-Central has an accessible picnic shelter (May 1 to October 31) with accessible parking, an accessible curb cut and path from parking to picnic shelter, and accessible path from picnic shelter to an accessible portable bathroom.

**Comment by alxstockdale** [comment]
@jim-z Revision required for the above

**Comment by jim-z** [comment]
updated in db
