### ISSUE TITLE
Remove trails_desc.csv file from repository

### ISSUE THREAD

**Issue by shua123** [fpdcc/webmap_data_updates#36]
It looks like trail descriptions are now kept in trail_desc.csv (no s). The outdated trail**s**_desc.csv should be removed to avoid confusion

**Comment by glw** [comment]
sorry about that. Ive fixed this, and created an export script for consistency in the future.

**Comment by shua123** [comment]
@glw Your latest update is now back to using trails_desc.csv instead of trail_desc.csv. Please decide on one so that my import script knows what file to read. :)

**Comment by glw** [comment]
yeah sorry for the flip-flop on the naming. I went back to the original convention, and automated the export so we shouldn't see and more file naming mix ups.
