### ISSUE TITLE
Updates for 6101 Oak Forest Avenue

### ISSUE THREAD

**Issue by alxstockdale** [fpdcc/webmap_data_updates#360]
## points_of_interest

**6101 Oak Forest Avenue** (poi_info_id=1193)

bathroom_portable_summer = 1
picnic_grove = 1

# poi_desc

**6101 Oak Forest Avenue** (poi_info_id=1193)

description = Nestled in Tinley Park's northeast corner, formerly Villa Santa Maria, this charming preserve is perfect for a leisurely walk through half a mile of tranquil grassy pathways amongst a landscape of oak woodland, wetlands and former agricultural fields. The site features an open area and picnic grove for visitors to enjoy.

# picnicgroves

**6101 Oak Forest Avenue**

picnicgrove_id = ?
preserve_name = 6101 Oak Forest Avenue
grove = 1
capacity = 50
large_capacity = no
grove_type = no shelter
location = Tinley Park, IL
accessible = no
poi_info_id = ?

**Comment by alxstockdale** [comment]
@jim-z Do we have official trails to be added here as well? I'll be dropping updates on new activities here as well.

**Comment by alxstockdale** [comment]
@jim-z Added additional info

**Comment by jim-z** [comment]
updated in db.  No official trails here yet.
