### ISSUE TITLE
Cal-Sag vs. Husar / Cal-Sag vs. Husar

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#80]
Shouldn't all this Purple be Cal-Sag? And that little bit of un-highlighted Red be Husar?

![image](https://user-images.githubusercontent.com/7032169/37622610-217ac4d6-2b90-11e8-9669-e1c0e8ad4b5f.png)

Shouldn't this Purple segment be Cal- Sag?
![image](https://user-images.githubusercontent.com/7032169/37622570-03af3f90-2b90-11e8-9483-31d26844afd6.png)

**Comment by glw** [comment]
For the John Husar Connector that segment was put in before the cal-sag. And I was basing the naming off of the documentation I found. Ive updated that small segment by grant rd, that show as on_fpdcc = yes to no. It is pretty confusing right there as to what is named what.

The cal-sag spur, Ive renamed to be trail_subsystem = 'Cal-Sag Trail'. So the mileage calculation will now be included as part of the main branch of the cal-sag trail.

It doesn't get reflected in the map but both of these segments are considered "connectors" and not part of the main branch. In our data they are differentiated with the "regional_trail_name" label, which is not used in the web map.
