### ISSUE TITLE
Dockless bikes

### ISSUE THREAD

**Issue by glw** [fpdcc/webmap_data_updates#89]
Include this in poi amenities?

**Comment by versatilehuman** [comment]
Yes, and in the activities data set. I'll send it over today.

**Comment by versatilehuman** [comment]
Ok, @glw has updates for **points_of_interest**, **activities** and **poi_desc** for the 50 dockless bike rental locations.

**Comment by versatilehuman** [comment]
@glw Looks like the activities for bike rentals didn't get updated.

**Comment by glw** [comment]
dockless points are now in activities.
