### ISSUE TITLE
Canoeing at Plank Road Boat Launch

### ISSUE THREAD

**Issue by jim-z** [fpdcc/webmap_data_updates#95]
canoeing icon missing from info panel

poi_info_id=253

change canoeing to =1

**Comment by versatilehuman** [comment]
@glw Reverse this. It's a boat launch and we are treating boat launch and canoe launch as mutually exclusive. It's either one or the other.

The canoeing column is for canoe launches, not for the activity of canoeing. That is covered through search: https://map.fpdcc.com/#/?search=canoe

**canoeing --> 0**
