### ISSUE TITLE
Extend FPDCC ownership of Major Taylor to 91st

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/webmap_data_updates#98]
"The City of Chicago conveyed its land and easement rights for the Major Taylor Trail from 80th Street to 91st Street to the FPCC in 2001. "

![image](https://user-images.githubusercontent.com/7032169/43347232-2c54661a-91ba-11e8-8075-ee71199be3a6.png)

**Comment by glw** [comment]
do you have the documentation for this? Id like to keep a link to that in the database as well.

**Comment by glw** [comment]
Spoke with John S. about this, and this parcel is not a part of any current agreement or right of way. It is a subject of discussion, so we'll have to stat tuned to see what happens.
