### ISSUE TITLE
Fishing at Oak Forest Heritage Preserve

### ISSUE THREAD

**Issue by jim-z** [fpdcc/webmap_data_updates#99]
Webmap indicates that fishing is allowed at Oak Forest west but not at Oak Forest east.  Should probably be one or the other.  Website does not currently list Oak Forest/Pogie Lake as a fishing lake.

https://map.fpdcc.com/#/?poi=365-Oak+Forest+Heritage+Preserve-East

**Comment by versatilehuman** [comment]
West is where there is legit access so I'd say keep it as is. 

Website doesn't have a list (will on the new website), but links to map of fishing areas.
